---
- name: Create Go Metalinter Directory
  become: true
  file:
    path: /opt/gometalinter/gometalinter-{{ gometalinter_version }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download Go Metalinter
  become: true
  get_url:
    url: "{{ gometalinter_download_url }}"
    dest: /opt/gometalinter/gometalinter-{{ gometalinter_version }}/gometalinter-{{ gometalinter_version }}.tar.gz

- name: Install Go Metalinter
  become: true
  unarchive:
    src: /opt/gometalinter/gometalinter-{{ gometalinter_version }}/gometalinter-{{ gometalinter_version }}.tar.gz
    dest: /opt/gometalinter/gometalinter-{{ gometalinter_version }}/
    extra_opts:
      - --strip-components=1

- name: Creating symlink to Go Metalinter
  become: true
  file:
    src: /opt/gometalinter/gometalinter-{{ gometalinter_version }}/bin/gometalinter
    dest: /usr/local/bin/gometalinter
    owner: root
    group: root
    mode: 0755
    state: link

